ezpublish:
    repositories:
        default:
            engine: legacy

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list: [demo_site]
        groups:
            demo_site_group: [demo_site]
        default_siteaccess: demo_site
        match:
            URIElement: 1

    system:
        demo_site_group:
            languages: [eng-GB]
            var_dir: var/ezdemo_site
